# Generated by Django 5.1.8 on 2025-06-16 15:11

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('active', models.BooleanField(verbose_name='active')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ca', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_gl', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_eu', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=400, verbose_name='description')),
                ('description_en', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('description_ca', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('description_gl', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('description_eu', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('description_es', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('description_nl', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('unit_of_analysis', models.CharField(choices=[('ORG', 'Organization'), ('PRO', 'Project'), ('EXT', 'External Survey')], default='ORG', max_length=3, verbose_name='unit of analysis')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('indicators', models.ManyToManyField(related_name='indicators', to='methods.indicator')),
                ('network_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.network')),
                ('related_legal_structures', models.ManyToManyField(related_name='structures', to='settings.legalstructure', verbose_name='Which entity does this method applies to?')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
