# Generated by Django 5.2.11 on 2026-03-04 17:21

import django.db.models.deletion
import sortedm2m.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0001_initial'),
        ('methods', '0001_initial'),
        ('organizations', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsurveyinvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='groupitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='group',
            name='items',
            field=models.ManyToManyField(related_name='groups', to='methods.groupitem'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='methods.group'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='group_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_2', to='methods.group'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='group_2_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_2_item', to='methods.groupitem'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='group_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_item', to='methods.groupitem'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.indicator'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='external_survey_invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='methods.externalsurveyinvitation'),
        ),
        migrations.AddField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='list_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_options', to='methods.list'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(related_name='lists', to='methods.listitem'),
        ),
        migrations.AddField(
            model_name='method',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='method',
            name='external_surveys',
            field=models.ManyToManyField(blank=True, to='methods.method', verbose_name='External surveys'),
        ),
        migrations.AddField(
            model_name='method',
            name='indicators',
            field=models.ManyToManyField(related_name='indicators', to='methods.indicator'),
        ),
        migrations.AddField(
            model_name='method',
            name='legal_structures',
            field=models.ManyToManyField(blank=True, related_name='structures', to='settings.legalstructure', verbose_name='Which entity does this method applies to?'),
        ),
        migrations.AddField(
            model_name='method',
            name='region1',
            field=models.ManyToManyField(related_name='region1', to='geodata.region1', verbose_name='Region1'),
        ),
        migrations.AddField(
            model_name='method',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='settings.sector', verbose_name='Sectors'),
        ),
        migrations.AddField(
            model_name='externalsurveyinvitation',
            name='external_survey',
            field=models.ForeignKey(limit_choices_to={'unit_of_analysis': 'EXT'}, on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='campaign_methods', to='methods.method', verbose_name='Methods'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='section',
            name='indicators',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='methods.indicator'),
        ),
        migrations.AddField(
            model_name='section',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='methods.section'),
        ),
        migrations.AddField(
            model_name='survey',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.campaign'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='survey',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
        migrations.AddField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.project'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.survey'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='methods.topic'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='methods.topic'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('email', 'external_survey_invitation'), name='pk_invitation'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.UniqueConstraint(fields=('survey', 'indicator', 'gender'), name='pk_indicator_result'),
        ),
    ]
