# Generated by Django 5.2.3 on 2025-08-21 14:59

import django.db.models.deletion
import project.models
import sortedm2m.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_ca', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_gl', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_eu', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_es', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_nl', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(verbose_name='order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('indicators', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='methods.indicator')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.method')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='methods.section')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
