# Generated by Django 5.2.6 on 2025-11-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='methods.topic'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='survey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='methods.survey'),
            preserve_default=False,
        ),
    ]
