# Generated by Django 5.2.3 on 2025-08-19 15:30

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
        ('organizations', '0001_initial'),
        ('settings', '0003_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('value', models.CharField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.campaign')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.gender')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.indicator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'indicator', 'organization', 'gender'), name='unique_pk')],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
