# Generated by Django 5.2.3 on 2025-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorresult',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
