# Generated by Django 5.2.6 on 2026-01-08 12:33

import django.db.models.deletion
import sortedm2m.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
        ('organizations', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='legal_structures',
            field=models.ManyToManyField(blank=True, related_name='structures', to='settings.legalstructure', verbose_name='Which entity does this method applies to?'),
        ),
        migrations.AddField(
            model_name='method',
            name='network_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.network'),
        ),
        migrations.AddField(
            model_name='method',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='settings.sector', verbose_name='Sectors'),
        ),
        migrations.AddField(
            model_name='externalsurveyinvitation',
            name='external_survey',
            field=models.ForeignKey(limit_choices_to={'unit_of_analysis': 'EXT'}, on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='methods',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('unit_of_analysis', 'EXT'), _negated=True), related_name='campaign_methods', to='methods.method', verbose_name='Methods'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='section',
            name='indicators',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='methods.indicator'),
        ),
        migrations.AddField(
            model_name='section',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='methods.section'),
        ),
        migrations.AddField(
            model_name='survey',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.campaign'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='survey',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
        migrations.AddField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.project'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.survey'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='methods.topic'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='methods.topic'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('email', 'external_survey_invitation'), name='pk_invitation'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.UniqueConstraint(fields=('survey', 'indicator', 'gender'), name='pk_indicator_result'),
        ),
    ]
