# Generated by Django 5.1.8 on 2025-06-17 08:24

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ca', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_gl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_eu', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_nl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('enable_others', models.BooleanField(default=False, verbose_name='Enable others response')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='list_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_options', to='methods.list'),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ca', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_gl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_eu', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_nl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('formula', models.CharField(max_length=50, verbose_name='formula')),
                ('value', models.PositiveSmallIntegerField(verbose_name='value')),
                ('active', models.BooleanField(max_length=50, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(related_name='items', to='methods.listitem'),
        ),
    ]
