# Generated by Django 5.2.11 on 2026-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='unit_of_analysis',
            field=models.CharField(choices=[('ORG', 'Organisation'), ('PRO', 'Project'), ('EXT', 'External Survey')], default='ORG', max_length=3, verbose_name='unit of analysis'),
        ),
    ]
