# Generated by Django 5.2.11 on 2026-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='display_indirect',
            field=models.BooleanField(default=False, verbose_name='Display indirect indicator?'),
        ),
    ]
