# Generated by Django 5.2.3 on 2025-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorresult',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Non binary')], default=None, null=True),
        ),
    ]
