# Generated by Django 5.2.6 on 2026-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
