# Generated by Django 5.2.6 on 2025-10-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('DL', '$'), ('K', 'kg'), ('M', 'm2'), ('T', '°C'), ('D', 'days'), ('P', 'points'), ('E', 'KWh')], default=None, verbose_name='unit'),
        ),
    ]
