# Generated by Django 5.1.8 on 2025-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='description_es',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_eu',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_gl',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_nl',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_eu',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_gl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_es',
            field=models.CharField(max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_eu',
            field=models.CharField(max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_gl',
            field=models.CharField(max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_eu',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_gl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
