# Generated by Django 5.2.11 on 2026-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='items',
            field=models.ManyToManyField(related_name='groups', to='methods.groupitem'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(related_name='lists', to='methods.listitem'),
        ),
    ]
