# Generated by Django 5.2.3 on 2025-07-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_list_alter_indicator_list_options_listitem_and_more'),
        ('methods', '0002_method'),
    ]

    operations = [
    ]
