# Generated by Django 5.2.3 on 2025-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_list_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='sub_data_type',
            field=models.CharField(choices=[('IG', 'Integer gendered value'), ('DG', 'Real gendered number')], default='IG', verbose_name='sub data type'),
        ),
    ]
