# Generated by Django 5.2.6 on 2025-10-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(limit_choices_to={'active': True}, related_name='items', to='methods.listitem'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='method',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
