# Generated by Django 5.2.6 on 2025-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed date'),
        ),
        migrations.AddField(
            model_name='survey',
            name='evaluated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Evaluated date'),
        ),
        migrations.AddField(
            model_name='survey',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified date'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AddField(
            model_name='survey',
            name='validated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validated date'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Tech validated'), (3, 'Quality checked')], default=0),
        ),
    ]
