# Generated by Django 5.2.11 on 2026-03-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_indicator_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='group_2_total',
            field=models.BooleanField(default=False, verbose_name='Add group totals?'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='group_total',
            field=models.BooleanField(default=False, verbose_name='Add group total?'),
        ),
    ]
