# Generated by Django 5.2.3 on 2025-09-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_alter_indicatorresult_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
    ]
