# Generated by Django 5.2.9 on 2026-02-10 17:16

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_alter_indicator_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_group_indicator',
            field=models.BooleanField(default=False, verbose_name='Is it a group indicator? (e.g. lists or tables)'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ca', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_gl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_eu', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_nl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='indicator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='methods.group'),
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_ca', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_gl', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_eu', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_nl', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('suffix', models.CharField(max_length=300, unique=True, verbose_name='suffix')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='group',
            name='items',
            field=models.ManyToManyField(related_name='items', to='methods.groupitem'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='group_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='methods.groupitem'),
        ),
    ]
