# Generated by Django 5.2.6 on 2025-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_alter_indicator_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='mandatory',
            field=models.BooleanField(default=True, verbose_name='Is it mandatory?'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='not_applicable',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='not applicable'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('DL', '$'), ('K', 'kg'), ('M', 'm2'), ('T', '°C'), ('D', 'days'), ('P', 'points'), ('E', 'KWh'), ('EH', '€/h')], default=None, verbose_name='unit'),
        ),
    ]
