# Generated by Django 5.2.9 on 2026-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_alter_indicator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, choices=[('PE', 'people'), ('DL', '$'), ('EU', '€'), ('K', 'kg'), ('M', 'm2'), ('T', '°C'), ('D', 'days'), ('P', 'points'), ('E', 'KWh'), ('EH', '€/h'), ('N', 'number'), ('PER', 'percentage')], default=None, null=True, verbose_name='unit'),
        ),
    ]
