# Generated by Django 5.2.11 on 2026-03-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_indicator_group_2_total_indicator_group_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorresult',
            name='is_total',
            field=models.BooleanField(default=False, verbose_name='Is total?'),
        ),
    ]
