# Generated by Django 5.2.3 on 2025-08-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_remove_campaign_methods_externalsurveyinvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsurveyinvitation',
            name='external_survey',
            field=models.ForeignKey(limit_choices_to={False}, on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
    ]
