# Generated by Django 5.2.6 on 2025-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='dependant_indicators',
            field=models.JSONField(blank=True, null=True, verbose_name='dependant_indicators'),
        ),
    ]
