# Generated by Django 5.2.3 on 2025-08-07 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_remove_campaign_methods_survey_indicatorresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.UniqueConstraint(fields=('survey', 'indicator'), name='unique_pk'),
        ),
    ]
