# Generated by Django 5.2.6 on 2025-10-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_alter_topic_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='project_id',
            new_name='code',
        ),
    ]
