# Generated by Django 5.2.9 on 2026-02-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_indicator_is_group_indicator_group_indicator_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='group_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_2', to='methods.group'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='group_2_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_2_item', to='methods.groupitem'),
        ),
        migrations.AlterField(
            model_name='indicatorresult',
            name='group_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_item', to='methods.groupitem'),
        ),
    ]
