# Generated by Django 5.2.6 on 2025-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0005_indicator_dependant_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='mandatory',
            field=models.BooleanField(default=True, verbose_name='Is it mandatory?'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='not_applicable',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='not applicable'),
        ),
    ]
