# Generated by Django 5.2.3 on 2025-08-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0005_alter_externalsurveyinvitation_external_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsurveyinvitation',
            name='external_survey',
            field=models.ForeignKey(limit_choices_to={'unit_of_analysis': 'EXT'}, on_delete=django.db.models.deletion.PROTECT, to='methods.method'),
        ),
    ]
