# Generated by Django 5.2.12 on 2026-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0006_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, choices=[('PE', 'people'), ('DL', '$'), ('EU', '€'), ('K', 'kg'), ('M', 'm2'), ('T', '°C'), ('D', 'days'), ('P', 'points'), ('E', 'KWh'), ('EH', '€/h'), ('N', 'number'), ('PER', '%')], default=None, null=True, verbose_name='unit'),
        ),
    ]
