# Generated by Django 5.2.3 on 2025-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0006_alter_externalsurveyinvitation_external_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='methods',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('unit_of_analysis', 'EXT'), _negated=True), related_name='campaign_methods', to='methods.method', verbose_name='Methods'),
        ),
    ]
