# Generated by Django 5.2.12 on 2026-03-25 13:08

import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0006_section_description'),
    ]

    operations = [
        sortedm2m.operations.AlterSortedManyToManyField(
            model_name='list',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='methods.listitem'),
        ),
    ]
