# Generated by Django 5.2.12 on 2026-03-26 08:22

import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0006_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, choices=[('PE', 'people'), ('DL', '$'), ('EU', '€'), ('K', 'kg'), ('M', 'm2'), ('T', '°C'), ('D', 'days'), ('P', 'points'), ('E', 'KWh'), ('EH', '€/h'), ('N', 'number'), ('PER', '%')], default=None, null=True, verbose_name='unit'),
        ),
        sortedm2m.operations.AlterSortedManyToManyField(
            model_name='list',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='methods.listitem'),
        ),
    ]
