# Generated by Django 5.2.12 on 2026-04-07 10:41
# Modifieded to follow sortedm2m guidelines when migrating m2m field to sortedm2m: https://pypi.org/project/django-sortedm2m/ 

import django.db.models.deletion
import project.models
import sortedm2m.fields
import uuid
from django.conf import settings
from django.db import migrations, models
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0007_alter_indicator_unit_alter_list_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsurveyinvitation',
            name='campaign',
            field=models.ForeignKey(default='3e5ad869-20f6-4395-87cd-6806e8c65e28', on_delete=django.db.models.deletion.PROTECT, to='methods.campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='instance_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Set instance number'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_ca',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_es',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_eu',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_gl',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        sortedm2m.operations.AlterSortedManyToManyField(
            model_name='group',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='methods.groupitem'),
        ),
        migrations.AlterField(
            model_name='method',
            name='indicators',
            field=models.ManyToManyField(related_name='methods', to='methods.indicator'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='IndicatorsSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('version', models.CharField(max_length=4, verbose_name='version')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='set name')),
                ('name_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('name_ca', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('name_gl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('name_eu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('name_es', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('name_nl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('name_fr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='set name')),
                ('description', models.CharField(blank=True, max_length=2500, verbose_name='description')),
                ('description_en', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('description_ca', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('description_gl', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('description_eu', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('description_es', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('description_nl', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('description_fr', models.CharField(blank=True, max_length=2500, null=True, verbose_name='description')),
                ('instance_name', models.CharField(blank=True, max_length=1000, verbose_name='item name')),
                ('instance_name_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('instance_name_ca', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('instance_name_gl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('instance_name_eu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('instance_name_es', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('instance_name_nl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('instance_name_fr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='item name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('indicators', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='sets', to='methods.indicator')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='method',
            name='indicators_sets',
            field=models.ManyToManyField(related_name='methods', to='methods.indicatorsset'),
        ),
        migrations.AddField(
            model_name='section',
            name='indicators_sets',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='sections', to='methods.indicatorsset'),
        ),
    ]
