# Generated by Django 5.2.12 on 2026-04-01 11:24

import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0007_alter_indicator_unit_alter_list_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description_ca',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_es',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_eu',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_gl',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        sortedm2m.operations.AlterSortedManyToManyField(
            model_name='group',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='methods.groupitem'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Description'),
        ),
    ]
