# Generated by Django 5.2.12 on 2026-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0007_alter_indicator_unit_alter_list_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description_ca',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_es',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_eu',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_gl',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
