# Generated by Django 5.2.12 on 2026-03-31 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0007_alter_indicator_unit_alter_list_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsurveyinvitation',
            name='campaign',
            field=models.ForeignKey(default='8a285f7d-798c-4260-b541-5f0512c962dc',on_delete=django.db.models.deletion.PROTECT, to='methods.campaign'),
            preserve_default=False,
        ),
    ]
