# Generated by Django 5.2.12 on 2026-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0008_externalsurveyinvitation_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='indicators_sets',
            field=models.ManyToManyField(null=True, related_name='methods', to='methods.indicatorsset'),
        ),
    ]
