# Generated by Django 5.2.12 on 2026-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0009_alter_method_indicators_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='indicators_sets',
            field=models.ManyToManyField(blank=True, related_name='methods', to='methods.indicatorsset'),
        ),
    ]
