# Generated by Django 5.2.12 on 2026-04-08 09:31

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0010_alter_method_indicators_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='groups', to='methods.groupitem'),
        ),
    ]
