# Generated by Django 5.2.12 on 2026-04-08 10:10

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0011_alter_group_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='lists', to='methods.listitem'),
        ),
    ]
