# Generated by Django 5.2.13 on 2026-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0012_alter_list_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsset',
            name='condition',
            field=models.CharField(blank=True, max_length=400, verbose_name='condition'),
        ),
    ]
