# Generated by Django 5.2.14 on 2026-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0013_indicatorsset_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='display_title',
            field=models.BooleanField(blank=True, default=True, verbose_name='Display section title?'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='dependant_indicators',
            field=models.JSONField(blank=True, null=True, verbose_name='dependant indicators'),
        ),
    ]
