# Generated by Django 5.2.6 on 2025-11-12 22:25

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0001_initial'),
        ('methods', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('vat_number', models.CharField(max_length=30, verbose_name='vat number')),
                ('website', models.CharField(blank=True, default='', max_length=300, verbose_name='website')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('privacy_policy_accepted', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.country')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('legal_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_structure', to='settings.legalstructure')),
                ('methods', models.ManyToManyField(blank=True, related_name='methods', to='methods.method', verbose_name='Methods')),
                ('region3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.region3')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vat_number', models.CharField(max_length=30, verbose_name='vat number')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='description')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='contact person')),
                ('contact_email', models.CharField(blank=True, max_length=255, verbose_name='contact email')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='contact telephone')),
                ('main_action_scope', models.CharField(choices=[('CA', 'Community action'), ('SC', 'Social cohesion'), ('CULT', 'Culture'), ('SP', 'Sports'), ('CH', 'Childhood'), ('Y', 'Youth'), ('ELD', 'Elderly'), ('WF', 'Women - Feminism'), ('LGTBI', 'LGTBI'), ('H', 'Health'), ('INT', 'Interculturality'), ('FD', 'Funcional diversity'), ('ES', 'Environmental sustainability'), ('SE', 'Social and solidarity economy'), ('C', 'Commerce'), ('UP', 'Urban planning'), ('IC', 'International cooperation'), ('LE', 'Leisure education and educational services'), ('RNT', 'Research and new technologies'), ('NSE', 'Networks and support for entities'), ('O', 'Other')], default='CA', verbose_name='main scope of action')),
                ('secondary_action_scope', models.CharField(blank=True, choices=[('CA', 'Community action'), ('SC', 'Social cohesion'), ('CULT', 'Culture'), ('SP', 'Sports'), ('CH', 'Childhood'), ('Y', 'Youth'), ('ELD', 'Elderly'), ('WF', 'Women - Feminism'), ('LGTBI', 'LGTBI'), ('H', 'Health'), ('INT', 'Interculturality'), ('FD', 'Funcional diversity'), ('ES', 'Environmental sustainability'), ('SE', 'Social and solidarity economy'), ('C', 'Commerce'), ('UP', 'Urban planning'), ('IC', 'International cooperation'), ('LE', 'Leisure education and educational services'), ('RNT', 'Research and new technologies'), ('NSE', 'Networks and support for entities'), ('O', 'Other')], default='', verbose_name='secondary fields of action')),
                ('main_legal_entity_type', models.CharField(choices=[('N', 'Neighborhood'), ('D', 'District'), ('CM', 'City/Municipality'), ('C', 'County')], default='N', verbose_name='Main legal entity type')),
                ('secondary_legal_entity_type', models.CharField(choices=[('N', 'Neighborhood'), ('D', 'District'), ('CM', 'City/Municipality'), ('C', 'County')], default='N', verbose_name='Secondary legal entity type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('publish_results', models.BooleanField(blank=True, max_length=50, null=True, verbose_name='I want to make public the results')),
                ('authorize', models.BooleanField(max_length=50, verbose_name='Authorize the use of my data for inclusion in the final report')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.city')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('methods', models.ManyToManyField(blank=True, related_name='project_methods', to='methods.method', verbose_name='Methods')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
                ('region1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.region1')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
