# Generated by Django 5.2.6 on 2025-11-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contact_person',
            new_name='contact_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='region1',
        ),
        migrations.AddField(
            model_name='project',
            name='region3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.region3'),
        ),
    ]
