# Generated by Django 5.2.11 on 2026-02-23 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0001_initial'),
        ('methods', '0002_initial'),
        ('organizations', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_structure', to='settings.legalstructure'),
        ),
        migrations.AddField(
            model_name='organization',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='methods', to='methods.method', verbose_name='Methods'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.region1'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='organization_sectors', to='settings.sector', verbose_name='Sectors'),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.city'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='project',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='project_methods', to='methods.method', verbose_name='Methods'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='region1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.region1'),
        ),
    ]
