# Generated by Django 5.2.3 on 2025-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_indicator_sub_data_type'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='methods', to='methods.method', verbose_name='Methods'),
        ),
    ]
