# Generated by Django 5.2.6 on 2025-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='networks',
            field=models.ManyToManyField(related_name='organization_networks', to='settings.network'),
        ),
    ]
