# Generated by Django 5.2.3 on 2025-07-17 14:07

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='methods',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='legal_structure', chained_model_field='legal_structures', horizontal=True, related_name='methods', to='methods.method', verbose_name='Methods'),
        ),
    ]
