# Generated by Django 5.2.13 on 2026-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bs_allow_public',
            field=models.BooleanField(default=False, verbose_name='Allow infographics to be public'),
        ),
    ]
