# Generated by Django 5.2.11 on 2026-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authorize',
            field=models.BooleanField(max_length=50, verbose_name='Authorise the use of my data for inclusion in the final report'),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish_results',
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name='I want to make the results public'),
        ),
    ]
