# Generated by Django 5.2.14 on 2026-07-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_bs_allow_public'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='network_managed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_managed', to='settings.network', verbose_name='Network managed'),
        ),
    ]
