# Generated by Django 5.2.6 on 2026-01-08 12:33

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0001_initial'),
        ('methods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ca', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_gl', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_eu', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='settings.legalstructure')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('campaigns', models.ManyToManyField(related_name='network_campaigns', to='methods.campaign')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('indicators', models.ManyToManyField(related_name='network_indicators', to='methods.indicator')),
                ('methods', models.ManyToManyField(related_name='network_methods', to='methods.method')),
                ('parent_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='settings.network')),
                ('region3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_region3', to='geodata.region3')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_ca', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_gl', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_eu', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
