# Generated by Django 5.2.3 on 2025-09-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalstructure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['name']},
        ),
    ]
