# Generated by Django 5.2.6 on 2025-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='campaigns',
            field=models.ManyToManyField(related_name='network_campaigns', to='methods.campaign'),
        ),
        migrations.AddField(
            model_name='network',
            name='indicators',
            field=models.ManyToManyField(related_name='network_indicators', to='methods.indicator'),
        ),
        migrations.AddField(
            model_name='network',
            name='methods',
            field=models.ManyToManyField(related_name='network_methods', to='methods.method'),
        ),
    ]
