# Generated by Django 5.1.8 on 2025-06-16 09:54

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ca', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_gl', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_eu', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
