# Generated by Django 5.2.14 on 2026-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpserver',
            name='from_email',
            field=models.EmailField(default='', max_length=255, verbose_name='From email'),
        ),
    ]
