# Generated by Django 5.1.8 on 2025-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalstructure',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='legalstructure',
            name='name_eu',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='legalstructure',
            name='name_gl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='legalstructure',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
