# Generated by Django 5.1.8 on 2025-05-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalstructure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='settings.legalstructure'),
        ),
    ]
