# Generated by Django 5.2.6 on 2025-12-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('settings', '0002_network_campaigns_network_indicators_network_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='region3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_region3', to='geodata.region3'),
        ),
    ]
