# Generated by Django 5.2.16 on 2026-09-14 22:01

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0014_section_display_title_and_more'),
        ('settings', '0002_smtpserver_from_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGStamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(verbose_name='Name')),
                ('svg', models.FileField(blank=True, null=True, upload_to='stamps/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.campaign')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='svg_stamp', to='settings.network', verbose_name='Network')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
